<?xml version="1.0" encoding="x-cp20005"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ProEssentials.Chart.Net.Winforms" Version="10.0.0.24" />
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.58" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <None Update="phlib.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TLPMX_32.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>