<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="MainForm.resx" />
    <EmbeddedResource Include="ucMainView.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="ProEssentials.Chart.Net.Winforms" Version="10.0.0.24" />
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.58" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="MainForm - Copy.Logging.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
    <Compile Update="MainForm - Copy.PowerMeter.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
    <Compile Update="MainForm - Copy.TCSPC.cs">
      <SubType>Form</SubType>
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="phlib.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TLPMX_32.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>